version: '3'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=your_mysql_host
      - DB_PORT=3306
      - DB_USER=manzanas
      - DB_PASSWORD=manzanaspwd
      - DB_DATABASE=pruebasdb
    depends_on:
      - db
  db:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=manzanaspwd
      - MYSQL_DATABASE=pruebasdb
